SHELL := /bin/bash
DATA_DIR = data

# ---------- Fetch a csv version of Ciqual data. ----------

CIQUAL_CSV := $(DATA_DIR)/ciqual2020.csv
$(CIQUAL_CSV):
	DATA_DIR=$(DATA_DIR) python scripts/ciqual_fetch.py


# ---------- Fetch and reformat the intial version of the nutrient map (tracked in git and later changed manually). ----------

NUTRIENT_MAP_RECIPE_ESTIMATOR := $(DATA_DIR)/nutrient_map_recipe_estimator.csv
$(NUTRIENT_MAP_RECIPE_ESTIMATOR):
	DATA_DIR=$(DATA_DIR) python scripts/nutrient_map/nutrient_map_fetch.py

NUTRIENT_MAP := $(DATA_DIR)/nutrient_map.csv
$(NUTRIENT_MAP): $(NUTRIENT_MAP_RECIPE_ESTIMATOR)
	DATA_DIR=$(DATA_DIR) python scripts/nutrient_map/nutrient_map_reformat.py

# ---------- Fetch, extract and summarize the Recommendations from the Nordic Nutrition Recommendations 2023. ----------
# recommendations_nnr2023.csv is tracked in git but can be regenerated by deleting the file and running
# make data/recommendations_nnr2023.csv

NNR_HTML := $(DATA_DIR)/recommendations_nnr2023.html
NNR_EXTRACTED_TABLES := $(DATA_DIR)/recommendations_nnr2023/*.csv
NNR_SUMMARY_CSV := $(DATA_DIR)/recommendations_nnr2023.csv

$(NNR_HTML):
	DATA_DIR=$(DATA_DIR) python scripts/recommendations_nnr2023/recommendations_fetch.py

$(NNR_EXTRACTED_TABLES): $(NNR_HTML)
	DATA_DIR=$(DATA_DIR) python scripts/recommendations_nnr2023/recommendations_extract_tables.py

$(NNR_SUMMARY_CSV): $(NNR_EXTRACTED_TABLES)
	DATA_DIR=$(DATA_DIR) python scripts/recommendations_nnr2023/recommendations_summarize_general.py

# ---------- Price and product data specific for each OFF_USERNAME. ----------
USER_DATA := $(DATA_DIR)/user_data/$(OFF_USERNAME)
PRICES_JSON := $(USER_DATA)/prices.json
PRODUCTS_JSON := $(USER_DATA)/products.json
SUMMARY_CSV := $(USER_DATA)/product_prices_and_nutrients.csv
LOCATION_CSV := $(USER_DATA)/locations.csv

$(PRICES_JSON):
	DATA_DIR=$(DATA_DIR) SIZE=100 python scripts/prices_fetch.py

$(PRODUCTS_JSON):
	DATA_DIR=$(DATA_DIR) python scripts/products_fetch.py

$(SUMMARY_CSV): $(CIQUAL_CSV) $(PRICES_JSON) $(PRODUCTS_JSON) $(NUTRIENT_MAP)
	DATA_DIR=$(DATA_DIR) python scripts/products_summarize.py

$(LOCATION_CSV): $(PRICES_JSON)
	DATA_DIR=$(DATA_DIR) python scripts/locations_summarize.py

locations: $(LOCATION_CSV)

# ---------- Run the optmization dashboard. ----------

opt: $(SUMMARY_CSV) $(NUTRIENT_MAP) $(NNR_SUMMARY_CSV)
	DATA_DIR=$(DATA_DIR) python dietdashboard/app.py

# ---------- Run the diet logger. ----------

log: $(SUMMARY_CSV) $(NUTRIENT_MAP) $(NNR_SUMMARY_CSV)
	DATA_DIR=$(DATA_DIR) python dietlogger/app.py

# ---------- OCR. ----------

ocr:
	DATA_DIR=$(DATA_DIR) python datacollection/run_ocr.py

view-ocr:
	DATA_DIR=$(DATA_DIR) python datacollection/view_ocr_app.py

init-db:
	DATA_DIR=$(DATA_DIR) python datacollection/init_db.py

# ---------- Clean data. ----------

# cleans current OFF_USERNAME data
clean-user-data:
	rm -f $(PRICES_JSON)
	rm -f $(PRODUCTS_JSON)
	rm -f $(SUMMARY_CSV)
