SHELL := /bin/bash
DATA_DIR = data

# ---------- Fetch a csv version of Ciqual data. ----------

CIQUAL_CSV := $(DATA_DIR)/ciqual2020.csv
$(CIQUAL_CSV):
	DATA_DIR=$(DATA_DIR) python scripts/ciqual_fetch.py


# ---------- Fetch and reformat the intial version of the nutrient map (tracked in git and later changed manually). ----------

NUTRIENT_MAP_RECIPE_ESTIMATOR := $(DATA_DIR)/nutrient_map_recipe_estimator.csv
$(NUTRIENT_MAP_RECIPE_ESTIMATOR):
	DATA_DIR=$(DATA_DIR) python scripts/nutrient_map/nutrient_map_fetch.py

NUTRIENT_MAP := $(DATA_DIR)/nutrient_map.csv
$(NUTRIENT_MAP): $(NUTRIENT_MAP_RECIPE_ESTIMATOR)
	DATA_DIR=$(DATA_DIR) python scripts/nutrient_map/nutrient_map_reformat.py

update_nutrient_map_counts:
	DATA_DIR=$(DATA_DIR) python scripts/nutrient_map/nutrient_map_update_counts.py

# ---------- Fetch, extract and summarize the Recommendations from the Nordic Nutrition Recommendations 2023. ----------
# recommendations_nnr2023.csv is tracked in git but can be regenerated by deleting the file and running
# make data/recommendations_nnr2023.csv

NNR_HTML := $(DATA_DIR)/recommendations_nnr2023.html
NNR_EXTRACTED_TABLES := $(DATA_DIR)/recommendations_nnr2023/*.csv
NNR_SUMMARY_CSV := $(DATA_DIR)/recommendations_nnr2023.csv

$(NNR_HTML):
	DATA_DIR=$(DATA_DIR) python scripts/recommendations_nnr2023/recommendations_fetch.py

$(NNR_EXTRACTED_TABLES): $(NNR_HTML)
	DATA_DIR=$(DATA_DIR) python scripts/recommendations_nnr2023/recommendations_extract_tables.py

$(NNR_SUMMARY_CSV): $(NNR_EXTRACTED_TABLES)
	DATA_DIR=$(DATA_DIR) python scripts/recommendations_nnr2023/recommendations_summarize_general.py

# ---------- Run the optmization dashboard. ----------

opt:
	DATA_DIR=$(DATA_DIR) python dietdashboard/app.py

# ---------- Create the nutrient extraction template. ----------

template:
	DATA_DIR=$(DATA_DIR) python scripts/template_nutriments_query.py

# ---------- Run the diet logger. ----------

log: $(SUMMARY_CSV) $(NUTRIENT_MAP) $(NNR_SUMMARY_CSV)
	DATA_DIR=$(DATA_DIR) python dietlogger/app.py

# ---------- OCR. ----------

ocr:
	DATA_DIR=$(DATA_DIR) python datacollection/run_ocr.py

view-ocr:
	DATA_DIR=$(DATA_DIR) python datacollection/view_ocr_app.py

init-db:
	DATA_DIR=$(DATA_DIR) python datacollection/init_db.py

# ---------- Clean data. ----------

# cleans current OFF_USERNAME data
clean-user-data:
	rm -f $(PRICES_JSON)
	rm -f $(PRODUCTS_JSON)
	rm -f $(SUMMARY_CSV)
