-- Documentation here: https://ciqual.anses.fr/cms/sites/default/files/inline-files/Table%20CALNUT%202020_doc_FR_2020%2007%2007.pdf
-- From table 0 we get the food group and subgroup
-- From table 1 we get upper_bound, lower_bound, mean, and an indicator of the completeness of the data
-- Both tables are joined by the ALIM_CODE and FOOD_LABEL columns
CREATE OR REPLACE TABLE calnut AS
WITH
calnut_0 AS (
    SELECT ALIM_CODE, FOOD_LABEL,
    alim_grp_code, alim_grp_nom_fr,
    alim_ssgrp_code, alim_ssgrp_nom_fr,
    alim_ssssgrp_code, alim_ssssgrp_nom_fr
    FROM read_csv($calnut_0_path)
    WHERE HYPOTH = 'MB'  -- to only have one row per food
),
calnut_1 AS (
    SELECT ALIM_CODE, FOOD_LABEL, CONST_LABEL, CONST_CODE,
    CAST(indic_combl AS BOOL) as combl,
    CAST(REPLACE(LB, ',', '.') AS FLOAT) as lb,
    CAST(REPLACE(UB, ',', '.') AS FLOAT) as ub,
    CAST(REPLACE(MB, ',', '.') AS FLOAT) as mean,
    FROM read_csv($calnut_1_path)
),
/* Pivoting the table to have one row per food
Following is an illustrative example of before and after pivoting:
Before:
┌───────────┬─────────────────┬───────────────┬────────────┬─────────┬───────┬───────┬───────┐
│ ALIM_CODE │   FOOD_LABEL    │  CONST_LABEL  │ CONST_CODE │  combl  │  lb   │  ub   │ mean  │
│   int64   │     varchar     │    varchar    │   int64    │ boolean │ float │ float │ float │
├───────────┼─────────────────┼───────────────┼────────────┼─────────┼───────┼───────┼───────┤
│     12114 │ Gruyère         │ proteines_g   │      25000 │ false   │  28.4 │  28.4 │  28.4 │
│     12049 │ Saint-Marcellin │ proteines_g   │      25000 │ false   │  15.1 │  15.1 │  15.1 │
│     12114 │ Gruyère         │ ag_20_4_ara_g │      42046 │ true    │ 0.024 │ 0.025 │ 0.025 │
│     12049 │ Saint-Marcellin │ ag_20_4_ara_g │      42046 │ false   │  0.02 │  0.02 │  0.02 │
└───────────┴─────────────────┴───────────────┴────────────┴─────────┴───────┴───────┴───────┘
After:
┌───────────┬─────────────────┬────────────────┬──────────────────┬────────────────┬───────────────────┬──────────────────┬────────────────────┬──────────────────┬─────────────────────┐
│ ALIM_CODE │   FOOD_LABEL    │ proteines_g_lb │ proteines_g_mean │ proteines_g_ub │ proteines_g_combl │ ag_20_4_ara_g_lb │ ag_20_4_ara_g_mean │ ag_20_4_ara_g_ub │ ag_20_4_ara_g_combl │
│   int64   │     varchar     │     float      │      float       │     float      │      boolean      │      float       │       float        │      float       │       boolean       │
├───────────┼─────────────────┼────────────────┼──────────────────┼────────────────┼───────────────────┼──────────────────┼────────────────────┼──────────────────┼─────────────────────┤
│     12114 │ Gruyère         │           28.4 │             28.4 │           28.4 │ false             │            0.024 │              0.025 │            0.025 │ true                │
│     12049 │ Saint-Marcellin │           15.1 │             15.1 │           15.1 │ false             │             0.02 │               0.02 │             0.02 │ false               │
└───────────┴─────────────────┴────────────────┴──────────────────┴────────────────┴───────────────────┴──────────────────┴────────────────────┴──────────────────┴─────────────────────┘
*/
calnut_1_pivoted AS (
    SELECT ALIM_CODE, FOOD_LABEL,
MAX(CASE WHEN CONST_LABEL = 'acides_organiques_g' THEN lb END) as acides_organiques_g_lb,
MAX(CASE WHEN CONST_LABEL = 'acides_organiques_g' THEN mean END) as acides_organiques_g_mean,
MAX(CASE WHEN CONST_LABEL = 'acides_organiques_g' THEN ub END) as acides_organiques_g_ub,
MAX(CASE WHEN CONST_LABEL = 'acides_organiques_g' THEN combl END) as acides_organiques_g_combl,
MAX(CASE WHEN CONST_LABEL = 'ag_04_0_g' THEN lb END) as ag_04_0_g_lb,
MAX(CASE WHEN CONST_LABEL = 'ag_04_0_g' THEN mean END) as ag_04_0_g_mean,
MAX(CASE WHEN CONST_LABEL = 'ag_04_0_g' THEN ub END) as ag_04_0_g_ub,
MAX(CASE WHEN CONST_LABEL = 'ag_04_0_g' THEN combl END) as ag_04_0_g_combl,
MAX(CASE WHEN CONST_LABEL = 'ag_06_0_g' THEN lb END) as ag_06_0_g_lb,
MAX(CASE WHEN CONST_LABEL = 'ag_06_0_g' THEN mean END) as ag_06_0_g_mean,
MAX(CASE WHEN CONST_LABEL = 'ag_06_0_g' THEN ub END) as ag_06_0_g_ub,
MAX(CASE WHEN CONST_LABEL = 'ag_06_0_g' THEN combl END) as ag_06_0_g_combl,
MAX(CASE WHEN CONST_LABEL = 'ag_08_0_g' THEN lb END) as ag_08_0_g_lb,
MAX(CASE WHEN CONST_LABEL = 'ag_08_0_g' THEN mean END) as ag_08_0_g_mean,
MAX(CASE WHEN CONST_LABEL = 'ag_08_0_g' THEN ub END) as ag_08_0_g_ub,
MAX(CASE WHEN CONST_LABEL = 'ag_08_0_g' THEN combl END) as ag_08_0_g_combl,
MAX(CASE WHEN CONST_LABEL = 'ag_10_0_g' THEN lb END) as ag_10_0_g_lb,
MAX(CASE WHEN CONST_LABEL = 'ag_10_0_g' THEN mean END) as ag_10_0_g_mean,
MAX(CASE WHEN CONST_LABEL = 'ag_10_0_g' THEN ub END) as ag_10_0_g_ub,
MAX(CASE WHEN CONST_LABEL = 'ag_10_0_g' THEN combl END) as ag_10_0_g_combl,
MAX(CASE WHEN CONST_LABEL = 'ag_12_0_g' THEN lb END) as ag_12_0_g_lb,
MAX(CASE WHEN CONST_LABEL = 'ag_12_0_g' THEN mean END) as ag_12_0_g_mean,
MAX(CASE WHEN CONST_LABEL = 'ag_12_0_g' THEN ub END) as ag_12_0_g_ub,
MAX(CASE WHEN CONST_LABEL = 'ag_12_0_g' THEN combl END) as ag_12_0_g_combl,
MAX(CASE WHEN CONST_LABEL = 'ag_14_0_g' THEN lb END) as ag_14_0_g_lb,
MAX(CASE WHEN CONST_LABEL = 'ag_14_0_g' THEN mean END) as ag_14_0_g_mean,
MAX(CASE WHEN CONST_LABEL = 'ag_14_0_g' THEN ub END) as ag_14_0_g_ub,
MAX(CASE WHEN CONST_LABEL = 'ag_14_0_g' THEN combl END) as ag_14_0_g_combl,
MAX(CASE WHEN CONST_LABEL = 'ag_16_0_g' THEN lb END) as ag_16_0_g_lb,
MAX(CASE WHEN CONST_LABEL = 'ag_16_0_g' THEN mean END) as ag_16_0_g_mean,
MAX(CASE WHEN CONST_LABEL = 'ag_16_0_g' THEN ub END) as ag_16_0_g_ub,
MAX(CASE WHEN CONST_LABEL = 'ag_16_0_g' THEN combl END) as ag_16_0_g_combl,
MAX(CASE WHEN CONST_LABEL = 'ag_18_0_g' THEN lb END) as ag_18_0_g_lb,
MAX(CASE WHEN CONST_LABEL = 'ag_18_0_g' THEN mean END) as ag_18_0_g_mean,
MAX(CASE WHEN CONST_LABEL = 'ag_18_0_g' THEN ub END) as ag_18_0_g_ub,
MAX(CASE WHEN CONST_LABEL = 'ag_18_0_g' THEN combl END) as ag_18_0_g_combl,
MAX(CASE WHEN CONST_LABEL = 'ag_18_1_ole_g' THEN lb END) as ag_18_1_ole_g_lb,
MAX(CASE WHEN CONST_LABEL = 'ag_18_1_ole_g' THEN mean END) as ag_18_1_ole_g_mean,
MAX(CASE WHEN CONST_LABEL = 'ag_18_1_ole_g' THEN ub END) as ag_18_1_ole_g_ub,
MAX(CASE WHEN CONST_LABEL = 'ag_18_1_ole_g' THEN combl END) as ag_18_1_ole_g_combl,
MAX(CASE WHEN CONST_LABEL = 'ag_18_2_lino_g' THEN lb END) as ag_18_2_lino_g_lb,
MAX(CASE WHEN CONST_LABEL = 'ag_18_2_lino_g' THEN mean END) as ag_18_2_lino_g_mean,
MAX(CASE WHEN CONST_LABEL = 'ag_18_2_lino_g' THEN ub END) as ag_18_2_lino_g_ub,
MAX(CASE WHEN CONST_LABEL = 'ag_18_2_lino_g' THEN combl END) as ag_18_2_lino_g_combl,
MAX(CASE WHEN CONST_LABEL = 'ag_18_3_a_lino_g' THEN lb END) as ag_18_3_a_lino_g_lb,
MAX(CASE WHEN CONST_LABEL = 'ag_18_3_a_lino_g' THEN mean END) as ag_18_3_a_lino_g_mean,
MAX(CASE WHEN CONST_LABEL = 'ag_18_3_a_lino_g' THEN ub END) as ag_18_3_a_lino_g_ub,
MAX(CASE WHEN CONST_LABEL = 'ag_18_3_a_lino_g' THEN combl END) as ag_18_3_a_lino_g_combl,
MAX(CASE WHEN CONST_LABEL = 'ag_20_4_ara_g' THEN lb END) as ag_20_4_ara_g_lb,
MAX(CASE WHEN CONST_LABEL = 'ag_20_4_ara_g' THEN mean END) as ag_20_4_ara_g_mean,
MAX(CASE WHEN CONST_LABEL = 'ag_20_4_ara_g' THEN ub END) as ag_20_4_ara_g_ub,
MAX(CASE WHEN CONST_LABEL = 'ag_20_4_ara_g' THEN combl END) as ag_20_4_ara_g_combl,
MAX(CASE WHEN CONST_LABEL = 'ag_20_5_epa_g' THEN lb END) as ag_20_5_epa_g_lb,
MAX(CASE WHEN CONST_LABEL = 'ag_20_5_epa_g' THEN mean END) as ag_20_5_epa_g_mean,
MAX(CASE WHEN CONST_LABEL = 'ag_20_5_epa_g' THEN ub END) as ag_20_5_epa_g_ub,
MAX(CASE WHEN CONST_LABEL = 'ag_20_5_epa_g' THEN combl END) as ag_20_5_epa_g_combl,
MAX(CASE WHEN CONST_LABEL = 'ag_20_6_dha_g' THEN lb END) as ag_20_6_dha_g_lb,
MAX(CASE WHEN CONST_LABEL = 'ag_20_6_dha_g' THEN mean END) as ag_20_6_dha_g_mean,
MAX(CASE WHEN CONST_LABEL = 'ag_20_6_dha_g' THEN ub END) as ag_20_6_dha_g_ub,
MAX(CASE WHEN CONST_LABEL = 'ag_20_6_dha_g' THEN combl END) as ag_20_6_dha_g_combl,
MAX(CASE WHEN CONST_LABEL = 'agmi_g' THEN lb END) as agmi_g_lb,
MAX(CASE WHEN CONST_LABEL = 'agmi_g' THEN mean END) as agmi_g_mean,
MAX(CASE WHEN CONST_LABEL = 'agmi_g' THEN ub END) as agmi_g_ub,
MAX(CASE WHEN CONST_LABEL = 'agmi_g' THEN combl END) as agmi_g_combl,
MAX(CASE WHEN CONST_LABEL = 'agpi_g' THEN lb END) as agpi_g_lb,
MAX(CASE WHEN CONST_LABEL = 'agpi_g' THEN mean END) as agpi_g_mean,
MAX(CASE WHEN CONST_LABEL = 'agpi_g' THEN ub END) as agpi_g_ub,
MAX(CASE WHEN CONST_LABEL = 'agpi_g' THEN combl END) as agpi_g_combl,
MAX(CASE WHEN CONST_LABEL = 'ags_g' THEN lb END) as ags_g_lb,
MAX(CASE WHEN CONST_LABEL = 'ags_g' THEN mean END) as ags_g_mean,
MAX(CASE WHEN CONST_LABEL = 'ags_g' THEN ub END) as ags_g_ub,
MAX(CASE WHEN CONST_LABEL = 'ags_g' THEN combl END) as ags_g_combl,
MAX(CASE WHEN CONST_LABEL = 'alcool_g' THEN lb END) as alcool_g_lb,
MAX(CASE WHEN CONST_LABEL = 'alcool_g' THEN mean END) as alcool_g_mean,
MAX(CASE WHEN CONST_LABEL = 'alcool_g' THEN ub END) as alcool_g_ub,
MAX(CASE WHEN CONST_LABEL = 'alcool_g' THEN combl END) as alcool_g_combl,
MAX(CASE WHEN CONST_LABEL = 'amidon_g' THEN lb END) as amidon_g_lb,
MAX(CASE WHEN CONST_LABEL = 'amidon_g' THEN mean END) as amidon_g_mean,
MAX(CASE WHEN CONST_LABEL = 'amidon_g' THEN ub END) as amidon_g_ub,
MAX(CASE WHEN CONST_LABEL = 'amidon_g' THEN combl END) as amidon_g_combl,
MAX(CASE WHEN CONST_LABEL = 'beta_carotene_mcg' THEN lb END) as beta_carotene_mcg_lb,
MAX(CASE WHEN CONST_LABEL = 'beta_carotene_mcg' THEN mean END) as beta_carotene_mcg_mean,
MAX(CASE WHEN CONST_LABEL = 'beta_carotene_mcg' THEN ub END) as beta_carotene_mcg_ub,
MAX(CASE WHEN CONST_LABEL = 'beta_carotene_mcg' THEN combl END) as beta_carotene_mcg_combl,
MAX(CASE WHEN CONST_LABEL = 'calcium_mg' THEN lb END) as calcium_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'calcium_mg' THEN mean END) as calcium_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'calcium_mg' THEN ub END) as calcium_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'calcium_mg' THEN combl END) as calcium_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'cholesterol_mg' THEN lb END) as cholesterol_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'cholesterol_mg' THEN mean END) as cholesterol_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'cholesterol_mg' THEN ub END) as cholesterol_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'cholesterol_mg' THEN combl END) as cholesterol_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'cuivre_mg' THEN lb END) as cuivre_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'cuivre_mg' THEN mean END) as cuivre_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'cuivre_mg' THEN ub END) as cuivre_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'cuivre_mg' THEN combl END) as cuivre_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'eau_g' THEN lb END) as eau_g_lb,
MAX(CASE WHEN CONST_LABEL = 'eau_g' THEN mean END) as eau_g_mean,
MAX(CASE WHEN CONST_LABEL = 'eau_g' THEN ub END) as eau_g_ub,
MAX(CASE WHEN CONST_LABEL = 'eau_g' THEN combl END) as eau_g_combl,
MAX(CASE WHEN CONST_LABEL = 'fer_mg' THEN lb END) as fer_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'fer_mg' THEN mean END) as fer_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'fer_mg' THEN ub END) as fer_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'fer_mg' THEN combl END) as fer_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'fibres_g' THEN lb END) as fibres_g_lb,
MAX(CASE WHEN CONST_LABEL = 'fibres_g' THEN mean END) as fibres_g_mean,
MAX(CASE WHEN CONST_LABEL = 'fibres_g' THEN ub END) as fibres_g_ub,
MAX(CASE WHEN CONST_LABEL = 'fibres_g' THEN combl END) as fibres_g_combl,
MAX(CASE WHEN CONST_LABEL = 'fructose_g' THEN lb END) as fructose_g_lb,
MAX(CASE WHEN CONST_LABEL = 'fructose_g' THEN mean END) as fructose_g_mean,
MAX(CASE WHEN CONST_LABEL = 'fructose_g' THEN ub END) as fructose_g_ub,
MAX(CASE WHEN CONST_LABEL = 'fructose_g' THEN combl END) as fructose_g_combl,
MAX(CASE WHEN CONST_LABEL = 'galactose_g' THEN lb END) as galactose_g_lb,
MAX(CASE WHEN CONST_LABEL = 'galactose_g' THEN mean END) as galactose_g_mean,
MAX(CASE WHEN CONST_LABEL = 'galactose_g' THEN ub END) as galactose_g_ub,
MAX(CASE WHEN CONST_LABEL = 'galactose_g' THEN combl END) as galactose_g_combl,
MAX(CASE WHEN CONST_LABEL = 'glucides_g' THEN lb END) as glucides_g_lb,
MAX(CASE WHEN CONST_LABEL = 'glucides_g' THEN mean END) as glucides_g_mean,
MAX(CASE WHEN CONST_LABEL = 'glucides_g' THEN ub END) as glucides_g_ub,
MAX(CASE WHEN CONST_LABEL = 'glucides_g' THEN combl END) as glucides_g_combl,
MAX(CASE WHEN CONST_LABEL = 'glucose_g' THEN lb END) as glucose_g_lb,
MAX(CASE WHEN CONST_LABEL = 'glucose_g' THEN mean END) as glucose_g_mean,
MAX(CASE WHEN CONST_LABEL = 'glucose_g' THEN ub END) as glucose_g_ub,
MAX(CASE WHEN CONST_LABEL = 'glucose_g' THEN combl END) as glucose_g_combl,
MAX(CASE WHEN CONST_LABEL = 'iode_mcg' THEN lb END) as iode_mcg_lb,
MAX(CASE WHEN CONST_LABEL = 'iode_mcg' THEN mean END) as iode_mcg_mean,
MAX(CASE WHEN CONST_LABEL = 'iode_mcg' THEN ub END) as iode_mcg_ub,
MAX(CASE WHEN CONST_LABEL = 'iode_mcg' THEN combl END) as iode_mcg_combl,
MAX(CASE WHEN CONST_LABEL = 'lactose_g' THEN lb END) as lactose_g_lb,
MAX(CASE WHEN CONST_LABEL = 'lactose_g' THEN mean END) as lactose_g_mean,
MAX(CASE WHEN CONST_LABEL = 'lactose_g' THEN ub END) as lactose_g_ub,
MAX(CASE WHEN CONST_LABEL = 'lactose_g' THEN combl END) as lactose_g_combl,
MAX(CASE WHEN CONST_LABEL = 'lipides_g' THEN lb END) as lipides_g_lb,
MAX(CASE WHEN CONST_LABEL = 'lipides_g' THEN mean END) as lipides_g_mean,
MAX(CASE WHEN CONST_LABEL = 'lipides_g' THEN ub END) as lipides_g_ub,
MAX(CASE WHEN CONST_LABEL = 'lipides_g' THEN combl END) as lipides_g_combl,
MAX(CASE WHEN CONST_LABEL = 'magnesium_mg' THEN lb END) as magnesium_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'magnesium_mg' THEN mean END) as magnesium_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'magnesium_mg' THEN ub END) as magnesium_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'magnesium_mg' THEN combl END) as magnesium_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'maltose_g' THEN lb END) as maltose_g_lb,
MAX(CASE WHEN CONST_LABEL = 'maltose_g' THEN mean END) as maltose_g_mean,
MAX(CASE WHEN CONST_LABEL = 'maltose_g' THEN ub END) as maltose_g_ub,
MAX(CASE WHEN CONST_LABEL = 'maltose_g' THEN combl END) as maltose_g_combl,
MAX(CASE WHEN CONST_LABEL = 'manganese_mg' THEN lb END) as manganese_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'manganese_mg' THEN mean END) as manganese_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'manganese_mg' THEN ub END) as manganese_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'manganese_mg' THEN combl END) as manganese_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'nrj_kcal' THEN lb END) as nrj_kcal_lb,
MAX(CASE WHEN CONST_LABEL = 'nrj_kcal' THEN mean END) as nrj_kcal_mean,
MAX(CASE WHEN CONST_LABEL = 'nrj_kcal' THEN ub END) as nrj_kcal_ub,
MAX(CASE WHEN CONST_LABEL = 'nrj_kcal' THEN combl END) as nrj_kcal_combl,
MAX(CASE WHEN CONST_LABEL = 'nrj_kj' THEN lb END) as nrj_kj_lb,
MAX(CASE WHEN CONST_LABEL = 'nrj_kj' THEN mean END) as nrj_kj_mean,
MAX(CASE WHEN CONST_LABEL = 'nrj_kj' THEN ub END) as nrj_kj_ub,
MAX(CASE WHEN CONST_LABEL = 'nrj_kj' THEN combl END) as nrj_kj_combl,
MAX(CASE WHEN CONST_LABEL = 'phosphore_mg' THEN lb END) as phosphore_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'phosphore_mg' THEN mean END) as phosphore_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'phosphore_mg' THEN ub END) as phosphore_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'phosphore_mg' THEN combl END) as phosphore_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'polyols_g' THEN lb END) as polyols_g_lb,
MAX(CASE WHEN CONST_LABEL = 'polyols_g' THEN mean END) as polyols_g_mean,
MAX(CASE WHEN CONST_LABEL = 'polyols_g' THEN ub END) as polyols_g_ub,
MAX(CASE WHEN CONST_LABEL = 'polyols_g' THEN combl END) as polyols_g_combl,
MAX(CASE WHEN CONST_LABEL = 'potassium_mg' THEN lb END) as potassium_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'potassium_mg' THEN mean END) as potassium_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'potassium_mg' THEN ub END) as potassium_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'potassium_mg' THEN combl END) as potassium_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'proteines_g' THEN lb END) as proteines_g_lb,
MAX(CASE WHEN CONST_LABEL = 'proteines_g' THEN mean END) as proteines_g_mean,
MAX(CASE WHEN CONST_LABEL = 'proteines_g' THEN ub END) as proteines_g_ub,
MAX(CASE WHEN CONST_LABEL = 'proteines_g' THEN combl END) as proteines_g_combl,
MAX(CASE WHEN CONST_LABEL = 'retinol_mcg' THEN lb END) as retinol_mcg_lb,
MAX(CASE WHEN CONST_LABEL = 'retinol_mcg' THEN mean END) as retinol_mcg_mean,
MAX(CASE WHEN CONST_LABEL = 'retinol_mcg' THEN ub END) as retinol_mcg_ub,
MAX(CASE WHEN CONST_LABEL = 'retinol_mcg' THEN combl END) as retinol_mcg_combl,
MAX(CASE WHEN CONST_LABEL = 'saccharose_g' THEN lb END) as saccharose_g_lb,
MAX(CASE WHEN CONST_LABEL = 'saccharose_g' THEN mean END) as saccharose_g_mean,
MAX(CASE WHEN CONST_LABEL = 'saccharose_g' THEN ub END) as saccharose_g_ub,
MAX(CASE WHEN CONST_LABEL = 'saccharose_g' THEN combl END) as saccharose_g_combl,
MAX(CASE WHEN CONST_LABEL = 'sel_g' THEN lb END) as sel_g_lb,
MAX(CASE WHEN CONST_LABEL = 'sel_g' THEN mean END) as sel_g_mean,
MAX(CASE WHEN CONST_LABEL = 'sel_g' THEN ub END) as sel_g_ub,
MAX(CASE WHEN CONST_LABEL = 'sel_g' THEN combl END) as sel_g_combl,
MAX(CASE WHEN CONST_LABEL = 'selenium_mcg' THEN lb END) as selenium_mcg_lb,
MAX(CASE WHEN CONST_LABEL = 'selenium_mcg' THEN mean END) as selenium_mcg_mean,
MAX(CASE WHEN CONST_LABEL = 'selenium_mcg' THEN ub END) as selenium_mcg_ub,
MAX(CASE WHEN CONST_LABEL = 'selenium_mcg' THEN combl END) as selenium_mcg_combl,
MAX(CASE WHEN CONST_LABEL = 'sodium_mg' THEN lb END) as sodium_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'sodium_mg' THEN mean END) as sodium_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'sodium_mg' THEN ub END) as sodium_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'sodium_mg' THEN combl END) as sodium_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'sucres_g' THEN lb END) as sucres_g_lb,
MAX(CASE WHEN CONST_LABEL = 'sucres_g' THEN mean END) as sucres_g_mean,
MAX(CASE WHEN CONST_LABEL = 'sucres_g' THEN ub END) as sucres_g_ub,
MAX(CASE WHEN CONST_LABEL = 'sucres_g' THEN combl END) as sucres_g_combl,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b12_mcg' THEN lb END) as vitamine_b12_mcg_lb,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b12_mcg' THEN mean END) as vitamine_b12_mcg_mean,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b12_mcg' THEN ub END) as vitamine_b12_mcg_ub,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b12_mcg' THEN combl END) as vitamine_b12_mcg_combl,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b1_mg' THEN lb END) as vitamine_b1_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b1_mg' THEN mean END) as vitamine_b1_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b1_mg' THEN ub END) as vitamine_b1_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b1_mg' THEN combl END) as vitamine_b1_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b2_mg' THEN lb END) as vitamine_b2_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b2_mg' THEN mean END) as vitamine_b2_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b2_mg' THEN ub END) as vitamine_b2_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b2_mg' THEN combl END) as vitamine_b2_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b3_mg' THEN lb END) as vitamine_b3_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b3_mg' THEN mean END) as vitamine_b3_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b3_mg' THEN ub END) as vitamine_b3_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b3_mg' THEN combl END) as vitamine_b3_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b5_mg' THEN lb END) as vitamine_b5_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b5_mg' THEN mean END) as vitamine_b5_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b5_mg' THEN ub END) as vitamine_b5_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b5_mg' THEN combl END) as vitamine_b5_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b6_mg' THEN lb END) as vitamine_b6_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b6_mg' THEN mean END) as vitamine_b6_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b6_mg' THEN ub END) as vitamine_b6_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b6_mg' THEN combl END) as vitamine_b6_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b9_mcg' THEN lb END) as vitamine_b9_mcg_lb,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b9_mcg' THEN mean END) as vitamine_b9_mcg_mean,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b9_mcg' THEN ub END) as vitamine_b9_mcg_ub,
MAX(CASE WHEN CONST_LABEL = 'vitamine_b9_mcg' THEN combl END) as vitamine_b9_mcg_combl,
MAX(CASE WHEN CONST_LABEL = 'vitamine_c_mg' THEN lb END) as vitamine_c_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'vitamine_c_mg' THEN mean END) as vitamine_c_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'vitamine_c_mg' THEN ub END) as vitamine_c_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'vitamine_c_mg' THEN combl END) as vitamine_c_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'vitamine_d_mcg' THEN lb END) as vitamine_d_mcg_lb,
MAX(CASE WHEN CONST_LABEL = 'vitamine_d_mcg' THEN mean END) as vitamine_d_mcg_mean,
MAX(CASE WHEN CONST_LABEL = 'vitamine_d_mcg' THEN ub END) as vitamine_d_mcg_ub,
MAX(CASE WHEN CONST_LABEL = 'vitamine_d_mcg' THEN combl END) as vitamine_d_mcg_combl,
MAX(CASE WHEN CONST_LABEL = 'vitamine_e_mg' THEN lb END) as vitamine_e_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'vitamine_e_mg' THEN mean END) as vitamine_e_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'vitamine_e_mg' THEN ub END) as vitamine_e_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'vitamine_e_mg' THEN combl END) as vitamine_e_mg_combl,
MAX(CASE WHEN CONST_LABEL = 'vitamine_k1_mcg' THEN lb END) as vitamine_k1_mcg_lb,
MAX(CASE WHEN CONST_LABEL = 'vitamine_k1_mcg' THEN mean END) as vitamine_k1_mcg_mean,
MAX(CASE WHEN CONST_LABEL = 'vitamine_k1_mcg' THEN ub END) as vitamine_k1_mcg_ub,
MAX(CASE WHEN CONST_LABEL = 'vitamine_k1_mcg' THEN combl END) as vitamine_k1_mcg_combl,
MAX(CASE WHEN CONST_LABEL = 'vitamine_k2_mcg' THEN lb END) as vitamine_k2_mcg_lb,
MAX(CASE WHEN CONST_LABEL = 'vitamine_k2_mcg' THEN mean END) as vitamine_k2_mcg_mean,
MAX(CASE WHEN CONST_LABEL = 'vitamine_k2_mcg' THEN ub END) as vitamine_k2_mcg_ub,
MAX(CASE WHEN CONST_LABEL = 'vitamine_k2_mcg' THEN combl END) as vitamine_k2_mcg_combl,
MAX(CASE WHEN CONST_LABEL = 'zinc_mg' THEN lb END) as zinc_mg_lb,
MAX(CASE WHEN CONST_LABEL = 'zinc_mg' THEN mean END) as zinc_mg_mean,
MAX(CASE WHEN CONST_LABEL = 'zinc_mg' THEN ub END) as zinc_mg_ub,
MAX(CASE WHEN CONST_LABEL = 'zinc_mg' THEN combl END) as zinc_mg_combl
FROM calnut_1
GROUP BY ALIM_CODE, FOOD_LABEL
)
SELECT calnut_0.alim_ssssgrp_code, calnut_0.alim_ssgrp_code, calnut_0.alim_grp_code,
    calnut_1_pivoted.*,
    calnut_0.alim_ssssgrp_nom_fr, calnut_0.alim_ssgrp_nom_fr, calnut_0.alim_grp_nom_fr
FROM calnut_1_pivoted
INNER JOIN calnut_0 ON calnut_1_pivoted.ALIM_CODE = calnut_0.ALIM_CODE
ORDER BY calnut_0.alim_ssssgrp_code, calnut_0.alim_ssgrp_code, calnut_0.alim_grp_code, calnut_0.alim_code
